### ISSUE TITLE
Search always return empty array

### ISSUE THREAD

**Issue by lufias** [devloopsnet/laravel-scout-typesense-engine#1]
Hi.. first of all, thank you for the library.. but, somehow im facing some difficulty to make the search work. Upon creating a record into the database table, I can see scout engine work its magic to index the record into typesense server. I can verify this by directly do the search to typesense api. But, once i call the search function in my model, it just return empty array. Also, i found out that calling php artisan scout:import also not indexing my records.

**Comment by AbdullahFaqeir** [comment]
@lufias Hi,

You're most welcome, I appreciate it.

I'm sorry for the issue you're having regarding the search, would you please provide me with code snippets where you're configuring the scout to use typesense and how you're setting up your model.

Thanks.

**Comment by lufias** [comment]
I actually solved it yesterday.. forgot to update.. turn out i just need to tweak my model a bit.. and i think the documentation need a bit more clarification.. the problem is that, laravel by default will set database id field to be of type integer and created_at field to be date time string.. unfortunately, typesense expect id to be a string while sorting field (created_at) to be int32. And i really couldn't find example on how to use 'toSearchableArray'. I thought it mean to further format the search result. Actually its to format the data to be provided to typesense. I got mine to work like this. Maybe you may consider to add this to the documentation update. Thanks.

```
    public function toSearchableArray()
    {
        $array = $this->toArray();        

        $array['id'] = (string)$array['id'];
        $array['created_at'] = (integer)Carbon::parse($array['created_at'])->timestamp;

        return $array;
    }

    public function getCollectionSchema(): array {
    	return [
    		'name' => $this->getTable(),
    		'fields' => [                   			                          
                [
    			'name' => 'name',
    			'type' => 'string',
    	        ],
                [
                    'name' => 'created_at',
                    'type' => 'int32',
                ],
    		],    
    		'default_sorting_field' => 'created_at',
    	];
    }

    public function typesenseQueryBy(): array {
      return [
        'name',
      ];
    }
```

**Comment by AbdullahFaqeir** [comment]
Hi @lufias,

Thank you for your update, I'm glad you managed to solve it yourself, and I apologize for the poor documentation, a new update will be coming soon adopting the new typesense php sdk which supports typesense 0.12.0 and will make sure to update the document to include your example.

Closing this issue.

Thanks.
