### ISSUE TITLE
Update `config/scout.php` example in Readme

### ISSUE THREAD

**Issue by manavo** [devloopsnet/laravel-scout-typesense-engine#16]
Based on the [v4 tag](https://github.com/devloopsnet/laravel-scout-typesense-engine/compare/v3.0.2...v4.0#diff-974f6d1a67e9e00e913b8428cb4cd7225f5e4a2b7b9e7117dc428268ed8be997L58), it looks like the readme is now out of date?

Looks like a very different list of values that would be needed? Or at least their structure in the array?

**Comment by rleger** [comment]
Yes, can't figure out the config that would be needed.

**Comment by AbdullahFaqeir** [comment]
I've fixed this issue and it's tagged with release #v4.0.1.

you can use the same configuration mentioned in the readme.
