### ISSUE TITLE
Upgrading from 2.0 to 3.0 does not work

### ISSUE THREAD

**Issue by jebede** [devloopsnet/laravel-scout-typesense-engine#8]
When using Laravel 6 and upgrading, I get the error when doing a Laravel Scout Product::search('term'):

``...typesense.net/collections` resulted in a `409 Conflict` response: {"message": "Collection with name `products` already exists."}``

**Comment by jebede** [comment]
When doing  php artisan scout:import it also gives the error:

`Symfony\Component\Debug\Exception\FatalThrowableError  : syntax error, unexpected 'Configuration' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)`

**Comment by AbdullahFaqeir** [comment]
Hi @jebede,

Can you please provide me with the php version you're using, as for what I'm seeing, it seems that the php version is not identifying the return type or parameter types, and it sees the class name as a constant.

Provide me with a dump of your environment details.

Cheers.

**Comment by jebede** [comment]
I'm using PHP7.4

**Comment by AbdullahFaqeir** [comment]
> When using Laravel 6 and upgrading, I get the error when doing a Laravel Scout Product::search('term'):
> 
> `` ...typesense.net/collections` resulted in a `409 Conflict` response: {"message": "Collection with name `products` already exists."} ``

Please run `php artisan scout:flush` and then try to search again.

**Comment by AbdullahFaqeir** [comment]
> When doing php artisan scout:import it also gives the error:
> 
> `Symfony\Component\Debug\Exception\FatalThrowableError : syntax error, unexpected 'Configuration' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)`

Can you please provide me with more details in order to asset you with your issue.

**Comment by jebede** [comment]
Thanks for thinking along. I tried php artisan scout:flush. I'm using Laravel 6.19.1, Guzzle 7.2, PHP7.4.

**Comment by AbdullahFaqeir** [comment]
Hi @jebede can you please provide me with the typesense-sdk version installed?

**Comment by jebede** [comment]
Hi @AbdullahFaqeir, I only installed devloopsnet/laravel-typesense v3.0.1, so I think the typesense-sdk got automatically installed that is required in the dependencies.

**Comment by AbdullahFaqeir** [comment]
Hi @jebede,

That's the issue, typesense-sdk got major updates and is now officially adopted by typesense.org

You need to make sure to update this driver to the very latest update and make sure it'll install the sdk from typesense repo.

Thanks.

**Comment by AbdullahFaqeir** [comment]
Hi @jebede 

Still facing this issue? can I assist you more with it? or shall I close this issue?
